### PR TITLE
Initial configuration of the backend stack

### PR DESCRIPTION
**Pull request by mateuszzalewski011**

### CODE REVIEW

**Review by Argmaster — APPROVED** [review]
Well, I think we will leave it as-is as it will require quite some work to consolidate it with frontend and standard project layout

**Comment by Argmaster** [comment]
Please fill all pull request properties.
image

**Review by Ave44 — APPROVED** [review]
approved, but we need to change the name of "app" folder in order to make frontend working properly

**Comment by Argmaster** [comment]
> approved, but we need to change the name of "app" folder in order to make frontend working properly

Ideed, we will consolidate this with work done by @MatSzpy and afterwards with your frontend config @Ave44

**Pull request merged**
